language: php
php:
    - 5.4
    - 5.5
    
before_script:
    - echo "extension=zmq.so" | sudo tee -a ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer install --dev

script:
    - ./phpunit