parameters:
    neducatio_websocketnotification.wsn_server_pusher.class: Neducatio\WebSocketNotificationBundle\ServerPusher
          
services:
    neducatio_websocketnotification.wsn_server_pusher:
        class: %neducatio_websocketnotification.wsn_server_pusher.class%