parameters:
    neducatio_websocketnotification.wsn_server_connection.class: Neducatio\WebSocketNotificationBundle\ServerConnection
    neducatio_websocketnotification.wsn_server_logger.class: Neducatio\WebSocketNotification\Common\Logger
          
services:
    neducatio_websocketnotification.wsn_server_connection:
        class: %neducatio_websocketnotification.wsn_server_connection.class%
        
    neducatio_websocketnotification.wsn_server_logger:
        class: %neducatio_websocketnotification.wsn_server_logger.class%